name: Test (Backend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    name: Tests (Backend)
    runs-on: [ubuntu-latest]

    container:
      image: node:10

    services:
      postgres:
        image: postgres:12
        volumes:
          - ${{ github.workspace }}/provisioning/postgres/setup/:/docker-entrypoint-initdb.d/
          - ${{ github.workspace }}/provisioning/postgres/timed-test-data.sql:/tmp/timed-test-data.sql
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: customercenter
        ports:
          - '5432:5432'
      redis:
        image: redis:6
        ports:
          - '6379:6379'
      ldap:
        image: osixia/openldap:1.4.0
        volumes:
          - ${{ github.workspace }}/provisioning/ldap/ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
        env:
          LDAP_ORGANISATION: adsy
          LDAP_DOMAIN: adsy-ext.becs.adfinis-sygroup.ch
          LDAP_ADMIN_PASSWORD: 123qwe
          LDAP_OPENLDAP_UID: 1000
          LDAP_OPENLDAP_GID: 1000
          LDAP_TLS: false
          LDAP_BASE_DN: dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
        ports:
          - '4389:389'
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - '8025:8025'
    env:
      APPLICATION_NAME: Customer Center
      APPLICATION_HOST: loclhost

      IDP_HOST: http://keycloak:8080
      IDP_TOKEN_PATH: /auth/realms/master/protocol/openid-connect/token
      IDP_CLIENT_ID: timed-confidential
      IDP_CLIENT_SECRET: 802635ae-2395-4419-b15b-b09dc838db14

      TIMED_HOST: http://timedbackend
      TIMED_PREFIX: /api/v1

      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: customercenter

      REDIS_HOST: redis
      REDIS_PORT: 6379

      SMTP_PORT: 1025
      SMTP_HOST: mailhog
      SMTP_SECURE: false
      SMTP_REQUIRE_TLS: false
      SMTP_FROM: from@example.com
      SMTP_TO: to@example.com

      AUTH_SECRET: ponies
      AUTH_ROLE_ADMIN: employees
      AUTH_ROLE_EMPLOYEE: employees
      AUTH_EXPIRE_PASSWORD: 3600
      AUTH_USERS_SEARCH_BASE: cn=users,dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
      AUTH_USERS_SEARCH_FILTER: (uid={{username}})'
      AUTH_USERS_GROUPSEARCH_BASE: cn=groups,dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
      AUTH_USERS_GROUPSEARCH_FILTER: (&(|(uniqueMember={{dn}})(memberUid={{dn}}))(objectClass=posixGroup))
      AUTH_CUSTOMERS_SEARCH_BASE: ou=customers,dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
      AUTH_CUSTOMERS_SEARCH_FILTER: (uid={{username}})'
      AUTH_CUSTOMERS_GROUPSEARCH_BASE: ou=customers,dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
      AUTH_CUSTOMERS_GROUPSEARCH_FILTER: (&(|(uniqueMember={{dn}})(memberUid={{dn}}))(objectClass=posixGroup))

      LDAP_HOST: ldap://ldap:4389
      LDAP_BIND_DN: uid=Administrator,cn=users,dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
      LDAP_BIND_CREDENTIALS: univention

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn --cwd=backend install

      - name: Run migrations
        run: make -C backend/ test-migrations

      - name: Run tests
        run: yarn --cwd=backend test
